// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuvxifaiojfkphpoltca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1dnhpZmFpb2pma3BocG9sdGNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0MTA3MTUsImV4cCI6MjA4NDk4NjcxNX0.ZikLS4hYRXUyjx1yQtIXq44RdAOmNR8Q2OV6KdRzW8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});